export const listSentences = [
  "Amazingly few discotheques provide jukeboxes.",
  "Back in June we delivered oxygen equipment of the same size.",
  "Crazy Fredrick bought many very exquisite opal jewels.",
  "Few black taxis drive up major roads on quiet hazy nights.",
  "Grumpy wizards make toxic brew for the evil Queen and Jack.",
  "Jackdaws love my big sphinx of quartz.",
  "Jinxed wizards pluck ivy from the big quilt.",
  "Pack my box with five dozen liquor jugs.",
  "The quick brown fox jumps over the lazy dog.",
  "The five boxing wizards jump quickly.",
  "Vampire bats quizzed Jim Crow about the next weapon.",
  "Waltz, bad nymph, for quick jigs vex.",
  "How razorback-jumping frogs can level six piqued gymnasts!",
  "Cozy lummox gives smart squid who asks for job pen.",
  "A quick movement of the enemy will jeopardize six gunboats.",
  "All questions asked by five watch experts amazed the judge.",
  "The quick onyx goblin jumps over the lazy dwarf.",
];
